sources:
  docker_logs:
    type: "docker_logs"
    exclude_containers:
      - "vector"

  http_telemetry:
    type: "http"
    address: "0.0.0.0:8080"
    decoding:
      codec: "json"

transforms:
  filter_project_logs:
    type: "filter"
    inputs:
      - "docker_logs"
    condition: '.label."com.docker.compose.project" == "${COMPOSE_PROJECT_NAME}"'

sinks:
  axiom_sink:
    type: "http"
    inputs:
      - "filter_project_logs"
    uri: "https://eu-central-1.aws.edge.axiom.co/v1/ingest/${AXIOM_DATASET}"
    encoding:
      codec: "json"
    request:
      headers:
        Authorization: "Bearer ${AXIOM_TOKEN}"
        Content-Type: "application/json"

  axiom_telemetry_sink:
    type: "http"
    inputs:
      - "http_telemetry"
    uri: "https://eu-central-1.aws.edge.axiom.co/v1/ingest/${AXIOM_TELEMETRY_DATASET:-jobby-telemetry}"
    encoding:
      codec: "json"
    request:
      headers:
        Authorization: "Bearer ${AXIOM_TOKEN}"
        Content-Type: "application/json"
