sources:
  docker_logs:
    type: "docker_logs"
    exclude_containers:
      - "vector"

sinks:
  axiom_sink:
    type: "http"
    inputs:
      - "docker_logs"
    uri: "https://eu-central-1.aws.edge.axiom.co/v1/ingest/${AXIOM_DATASET}"
    encoding:
      codec: "json"
    request:
      headers:
        Authorization: "Bearer ${AXIOM_TOKEN}"
        Content-Type: "application/json"
